# The Docker image that will be used to build your app
image: busybox
# Functions that should be executed before the build script is run
before_script:
  - echo "The site will be deployed to $CI_PAGES_URL"
